/**
 * Audit log primitive (Track F.2).
 *
 * Append-only log of sensitive operations. Used for:
 *   - Customer support: "who changed Sarah's role last Tuesday?"
 *   - Compliance: child-data access trail
 *   - Incident response: tracing what happened during an outage
 *   - Procurement: a real Activity feed builds trust with paying churches
 *
 * Schema is denormalized intentionally — each row is independently readable
 * and survives schema changes upstream. Writes are fire-and-forget;
 * audit-log failures must never block the actual business operation.
 *
 * Storage: top-level `audit_logs` collection. Firestore rules deny client
 * reads/writes; admin reads happen through /api/admin/audit-logs (Track F.3
 * builds the UI on top of this).
 */

import { adminDb } from "@/lib/firebase/admin";

/** Stable, lowercased dot-namespaced action identifier. */
export type AuditAction =
  // Schedule lifecycle
  | "schedule.publish"
  | "schedule.unpublish"
  | "schedule.delete"
  // Membership lifecycle
  | "membership.invite"
  | "membership.approve"
  | "membership.role_change"
  | "membership.remove"
  | "membership.deactivate"
  // Org lifecycle
  | "org.create"
  | "org.delete"
  | "org.tier_change"
  | "org.transfer_ownership"
  // Billing (Stripe)
  | "billing.subscription_created"
  | "billing.subscription_updated"
  | "billing.subscription_canceled"
  | "billing.invoice_paid"
  | "billing.invoice_failed"
  | "billing.dispute_created"
  // Platform admin
  | "platform.tier_override"
  | "platform.org_export"
  // Kiosk / check-in (children's data)
  | "kiosk.station_create"
  | "kiosk.station_revoke"
  | "kiosk.station_reissue_code"
  | "kiosk.activate"
  | "kiosk.lookup"
  | "kiosk.checkin"
  | "kiosk.checkout"
  | "kiosk.register_visitor"
  | "kiosk.medical_data_revealed"
  // Data export
  | "export.people"
  | "export.assignments"
  | "export.song_usage"
  | "export.attendance"
  // Short links
  | "short_link.create_external"
  // Generic catch-all so future ops can audit without a code change here
  | (string & { __brand?: "audit" });

export interface AuditEntry {
  /** Doc ID, autogenerated. */
  id?: string;
  /** Org scope. Null for platform-admin actions not tied to a single church. */
  church_id: string | null;
  /**
   * Acting principal. One of:
   *   - "user:<uid>"      authenticated user
   *   - "kiosk:<id>"      kiosk station
   *   - "system"          server-initiated (cron, webhook)
   *   - "platform_admin:<uid>"  acting in platform-admin capacity
   */
  actor: string;
  /** Snake/dot-cased action identifier; see AuditAction. */
  action: AuditAction;
  /** What was acted upon, if applicable. */
  target_type?: string | null;
  target_id?: string | null;
  /** Optional small JSON metadata blob. PII-redacted by callers. */
  metadata?: Record<string, unknown>;
  /** "ok" | "denied" | "failed" — distinguishes successful actions from denials. */
  outcome: "ok" | "denied" | "failed";
  /** ISO timestamp. */
  created_at: string;
  /** Optional request id for correlation with logs/Sentry. */
  request_id?: string | null;
}

/**
 * Write an audit log entry. Fire-and-forget; failures are swallowed and
 * logged to console (Sentry will pick them up if installed). Never blocks
 * the caller — if the audit write fails, the business op still succeeds.
 *
 * Note: PII redaction is the caller's responsibility. Don't put raw phone
 * numbers, child medical notes, etc. in metadata. Reference IDs only.
 */
export async function audit(entry: Omit<AuditEntry, "created_at" | "id">): Promise<void> {
  try {
    await adminDb.collection("audit_logs").add({
      ...entry,
      metadata: entry.metadata ?? {},
      created_at: new Date().toISOString(),
    });
  } catch (err) {
    console.error("[audit] write failed", { action: entry.action, err });
  }
}

/**
 * Convenience: build the actor string for an authenticated user. Use for
 * org-scoped actions performed by a logged-in admin.
 */
export function userActor(uid: string): string {
  return `user:${uid}`;
}

export function kioskActor(stationId: string): string {
  return `kiosk:${stationId}`;
}

export function platformAdminActor(uid: string): string {
  return `platform_admin:${uid}`;
}

export const SYSTEM_ACTOR = "system";
