import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Zilla_Slab } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AuthProvider } from "@/lib/context/auth-context";
import { ToastProvider } from "@/components/ui/toast";
import { ConfirmProvider } from "@/components/ui/confirm-dialog";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

const zillaSlab = Zilla_Slab({
  variable: "--font-zilla-slab",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "500", "600"],
});

export const metadata: Metadata = {
  title: "VolunteerCal — Flexible Volunteer Scheduling",
  description:
    "Auto-generate fair, conflict-free volunteer schedules across all your teams. Leaders review. Volunteers confirm. Works standalone or with Planning Center, Breeze, and Rock RMS.",
  keywords: [
    "volunteer scheduling",
    "church volunteer scheduling",
    "nonprofit volunteer management",
    "volunteer calendar",
    "scheduling software",
    "Planning Center alternative",
  ],
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/apple-touch-icon.svg",
  },
  manifest: "/manifest.json",
  openGraph: {
    title: "VolunteerCal — Flexible Volunteer Scheduling",
    description:
      "Auto-generate fair, conflict-free volunteer schedules. Leaders review. Volunteers confirm and sync to their calendar.",
    url: "https://volunteercal.com",
    siteName: "VolunteerCal",
    type: "website",
    // OG image auto-generated by opengraph-image.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#2D3A6E" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </head>
      <body
        className={`${plusJakartaSans.variable} ${zillaSlab.variable} font-sans antialiased`}
      >
        {/* Skip-to-main for keyboard accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-vc-indigo focus:px-4 focus:py-2 focus:text-white focus:shadow-lg"
        >
          Skip to main content
        </a>
        <AuthProvider>
          <ToastProvider>
            <ConfirmProvider>{children}</ConfirmProvider>
          </ToastProvider>
        </AuthProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
