import type { Metadata } from "next";
import { DM_Sans, DM_Serif_Display } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AuthProvider } from "@/lib/context/auth-context";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "VolunteerCal — Flexible Volunteer Scheduling for Churches, Nonprofits & Teams",
  description:
    "Auto-generate fair, conflict-free volunteer schedules across all your teams. Leaders review. Volunteers confirm. Works standalone or with Planning Center, Breeze, and Rock RMS.",
  keywords: [
    "volunteer scheduling",
    "church volunteer scheduling",
    "nonprofit volunteer management",
    "volunteer calendar",
    "scheduling software",
    "Planning Center alternative",
  ],
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/apple-touch-icon.svg",
  },
  manifest: "/manifest.json",
  openGraph: {
    title: "VolunteerCal — Flexible Volunteer Scheduling for Churches, Nonprofits & Teams",
    description:
      "Auto-generate fair, conflict-free volunteer schedules. Leaders review. Volunteers confirm and sync to their calendar.",
    url: "https://volunteercal.com",
    siteName: "VolunteerCal",
    type: "website",
    // OG image auto-generated by opengraph-image.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#2D3A6E" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </head>
      <body
        className={`${dmSans.variable} ${dmSerifDisplay.variable} font-sans antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
