// AUTO-GENERATED by /tmp/md2jsx.py from
// docs/help-guides/checkin/published/*.md
// Do not edit by hand — re-run the converter and re-incorporate.

import Image from "next/image";
import type { ReactNode } from "react";

export interface CheckinGuide {
  slug: string;
  title: string;
  /** 1 = Anchor Falls priority, 2 = important for Sunday onward, 3 = operational completeness. */
  tier: 1 | 2 | 3;
  content: ReactNode;
}

export const CHECKIN_GUIDES: CheckinGuide[] = [
  // a1-kiosk-setup — tier 1
  {
    slug: "a1-kiosk-setup",
    title: "Set up your first check-in kiosk",
    tier: 1,
    content: (
      <>
      <p className="mt-3">This guide walks you through turning an iPad into a working check-in station for your church&apos;s lobby. By the end you&apos;ll have a kiosk bound to your church, set to the right type, and ready to check families in.</p>
      <p className="mt-3">You&apos;ll do most of this at a desk on your laptop, with the iPad you&apos;re enrolling sitting next to you.</p>
      <p className="mt-3"><strong>Before you start, you&apos;ll need:</strong></p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Your VolunteerCal organization created</li>
        <li className="mt-1">A plan on Growth tier or above (check-in requires it)</li>
        <li className="mt-1">At least one iPad or Android tablet</li>
        <li className="mt-1">That tablet on the same Wi-Fi as the rest of your church network</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">First, what a &quot;station&quot; is</h3>
      <p className="mt-3">Each physical iPad in your lobby is a <strong>station</strong>. Two things are true of every station, and both are set when you enroll it:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>It&apos;s bound to one church.</strong> If you run more than one organization, a station tied to one church can&apos;t accidentally check families into the other.</li>
        <li className="mt-1"><strong>It has a type</strong> &mdash; staffed or self-service &mdash; that controls what it&apos;s allowed to do.</li>
      </ul>
      <p className="mt-3"><strong>The station type can&apos;t be changed after enrollment.</strong> If you pick the wrong one, you&apos;ll revoke the station and re-enroll the iPad with a fresh code. So it&apos;s worth getting right the first time. The next section covers the choice.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Choose a station type</h3>
      <p className="mt-3">This is the most important decision in setup. There are two types.</p>
      <p className="mt-3"><strong>Staffed kiosk</strong> &mdash; a volunteer stands at the kiosk and supervises every check-in. Staffed stations can do everything:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Regular check-in</li>
        <li className="mt-1">Pickup verification at checkout, including the blocked-pickup photo comparison</li>
        <li className="mt-1">Overriding the blocked-pickup gate when the operator confirms the person standing there isn&apos;t the blocked individual</li>
        <li className="mt-1">The &quot;I&apos;m here for pickup&quot; ping button</li>
      </ul>
      <p className="mt-3"><strong>Self-service kiosk</strong> &mdash; placed at a turnstile-style entrance where families check themselves in without a volunteer present. A self-service station:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Can</strong> do regular check-in</li>
        <li className="mt-1"><strong>Cannot</strong> do checkout &mdash; releasing a child always happens at a staffed kiosk, because the security gate is the parent&apos;s code, not the device</li>
        <li className="mt-1"><strong>Cannot</strong> override the blocked-pickup gate &mdash; if a block fires, that family has to go to a staffed station</li>
      </ul>
      <p className="mt-3"><strong>Recommendation:</strong> start with a staffed kiosk for your first deployment. You can add self-service stations later if your check-in volume calls for it.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Generate the activation code</h3>
      <figure className="my-4"><Image src="/help/checkin/a1-add-station-modal.png" alt="A1 add station modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">Go to <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Settings → Check-In → Stations</code></li>
        <li className="mt-1">Click <strong>Add station</strong></li>
        <li className="mt-1">Pick the station type (staffed or self-service, per above)</li>
        <li className="mt-1">Optionally give it a name &mdash; <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Lobby 1</code>, <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Children&apos;s wing</code>, anything that helps you tell stations apart. It&apos;s only for your reference</li>
        <li className="mt-1">Click <strong>Generate code</strong></li>
      </ol>
      <p className="mt-3">An 8-character code appears with a <strong>10-minute countdown</strong>.</p>
      <figure className="my-4"><Image src="/help/checkin/a1-activation-code-display.png" alt="A1 activation code display" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">Codes expire after 10 minutes for security. If yours runs out before you&apos;ve entered it, just click <strong>Generate code</strong> again &mdash; the modal stays open and gives you a fresh one.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Enroll the iPad</h3>
      <figure className="my-4"><Image src="/help/checkin/a1-ipad-enrollment-empty.png" alt="A1 ipad enrollment empty" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">On the iPad, open <strong>Safari</strong>. Not Chrome &mdash; the location-aware Apple Wallet pass and the full-screen install both need Safari to work</li>
        <li className="mt-1">Go to <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">https://volunteercal.com/checkin</code></li>
        <li className="mt-1">You&apos;ll see the <strong>Enroll this kiosk</strong> screen with an 8-character input box</li>
        <li className="mt-1">Type or paste in the activation code. Capitalization doesn&apos;t matter</li>
      </ol>
      <figure className="my-4"><Image src="/help/checkin/a1-ipad-enrollment-with-code.png" alt="A1 ipad enrollment with code" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">Tap <strong>Activate kiosk</strong></li>
      </ol>
      <p className="mt-3">The iPad binds to your church and switches to the kiosk landing screen. That&apos;s a working station.</p>
      <figure className="my-4"><Image src="/help/checkin/a1-kiosk-landing-after-activation.png" alt="A1 kiosk landing after activation" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Add it to the Home Screen (recommended)</h3>
      <p className="mt-3">This step is optional, but it makes the kiosk feel like a real app instead of a browser tab &mdash; full screen, no Safari toolbar, and the kiosk address saved so you never have to retype it.</p>
      <div className="my-4 rounded-lg border-2 border-dashed border-vc-border bg-vc-bg-warm/40 p-4 text-sm text-vc-text-muted"><strong>Screenshot pending:</strong> <code>a1-ipad-pwa-add-to-home-screen</code> &mdash; see <code>docs/help-guides/checkin/inbox-codex/SKIPPED.md</code></div>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">On the kiosk landing screen, tap the Safari <strong>share button</strong> (the square with an arrow pointing up)</li>
        <li className="mt-1">Choose <strong>Add to Home Screen</strong></li>
        <li className="mt-1">Name it <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Check-In</code> (or whatever you like) and tap <strong>Add</strong></li>
      </ol>
      <p className="mt-3">From now on, open the kiosk from that home screen icon for full-screen mode.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Finish your check-in setup</h3>
      <p className="mt-3">The station is ready, but a few settings make Sunday morning run smoothly. Set these before your first service:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Service times</strong> &mdash; <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Settings → Check-In → Service Times</code>. This tells the kiosk when to open and close check-in, and when to start treating a child as arriving late</li>
        <li className="mt-1"><strong>Rooms</strong> &mdash; <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Settings → Check-In → Rooms</code>. With rooms configured, children get auto-assigned by grade at check-in</li>
        <li className="mt-1"><strong>Label printer (optional)</strong> &mdash; <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Settings → Check-In → Printers</code>. VolunteerCal supports the Brother QL-820NWB, Zebra ZD, and Dymo printers. See the <strong>Label printing</strong> guide for the full walkthrough</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">If something doesn&apos;t go as expected</h3>
      <p className="mt-3"><strong>&quot;I generated a code but didn&apos;t enter it in time.&quot;</strong> Generate another. The modal stays open and the old code simply stops working.</p>
      <p className="mt-3"><strong>&quot;I picked the wrong station type.&quot;</strong> Revoke the station from <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Settings → Check-In → Stations</code>, generate a new code with the correct type, and re-enroll the iPad with it.</p>
      <p className="mt-3"><strong>&quot;The iPad says &apos;Invalid activation code.&apos;&quot;</strong> Most often the code expired (codes last 10 minutes). Generate a fresh one and try again.</p>
      <p className="mt-3"><strong>&quot;The iPad just shows a spinner that never finishes.&quot;</strong> The tablet needs internet &mdash; check that it&apos;s connected to Wi-Fi. If it&apos;s online and still spinning, Safari may be holding onto stale sign-in data. Open one Safari Private window, then close it, and reload the kiosk page to reset.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Messages you might see</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>&quot;Invalid code format&quot;</strong> &mdash; the code has to be exactly 8 characters. Re-check what you typed</li>
        <li className="mt-1"><strong>&quot;Code expired&quot;</strong> &mdash; the 10-minute window passed. Generate a new code from the Stations settings page</li>
        <li className="mt-1"><strong>&quot;Code already used&quot;</strong> &mdash; each code works once. Generate a new one to enroll another station</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk on Sunday morning</strong> (what to do once the station is live)</li>
        <li className="mt-1"><strong>Label printing setup</strong> (optional)</li>
        <li className="mt-1"><strong>Service times configuration</strong></li>
      </ul>
      </>
    ),
  },
  // a2-kiosk-runtime — tier 1
  {
    slug: "a2-kiosk-runtime",
    title: "Running the kiosk on Sunday morning",
    tier: 1,
    content: (
      <>
      <p className="mt-3">This is the screen you&apos;ll work from all morning. It covers checking in a returning family, registering a new one, handling allergy and medical alerts, choosing who can pick up, and what the security code is for.</p>
      <p className="mt-3"><strong>Before you start:</strong> the kiosk should be enrolled and powered on, and your service times set so check-in is open.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Finding a family &mdash; three ways</h3>
      <p className="mt-3">At the start screen, a family can be looked up one of three ways. Use whichever is fastest.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-start-screen.png" alt="A2 kiosk start screen" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Apple Wallet pass scan</strong> &mdash; the quickest. The parent taps their pass on their iPhone and holds it up to the kiosk camera, which reads the code. Works for families who&apos;ve already added the pass.</li>
        <li className="mt-1"><strong>Printed QR card</strong> &mdash; if the family carries their household QR card (created from their household page in the admin), scan it the same way.</li>
        <li className="mt-1"><strong>Last 4 digits of phone</strong> &mdash; the reliable fallback. Tap <strong>Find by phone</strong>, enter the last four digits, and the kiosk lists matching families. Collisions are rare; if two families match, ask for the full number.</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-qr-scanner-active.png" alt="A2 kiosk qr scanner active" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-phone-last4.png" alt="A2 kiosk phone last4" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3"><strong>First time here?</strong> Tap <strong>New family</strong> on the start screen to register them on the spot.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Choosing who&apos;s checking in</h3>
      <p className="mt-3">Once the household is found, each child shows as a tappable card.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-child-selection-with-badges.png" alt="A2 kiosk child selection with badges" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">Each card has a photo (or an initial in a circle), the child&apos;s name, a grade chip, and their assigned room. Some cards carry a badge:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Allergy</strong> (red) &mdash; the child has a medical alert on file. You&apos;ll see the details on the next step</li>
        <li className="mt-1"><strong>Pickup note</strong> (amber, with a lock icon) &mdash; the household has a pickup restriction on file. It&apos;s intentionally discreet so a child or parent glancing at the screen won&apos;t see private details. You don&apos;t do anything about it now &mdash; the system handles it at checkout</li>
        <li className="mt-1"><strong>Pre-checked in</strong> (sage) &mdash; the family completed check-in online before arriving. (This appears once online pre-check-in is available.)</li>
      </ul>
      <p className="mt-3">Tap a card to select it. Tap several cards to check in siblings together.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Acknowledging allergy and medical alerts</h3>
      <p className="mt-3">If any selected child has alerts, the kiosk shows the actual details &mdash; allergies, medications, medical notes &mdash; and asks you to tap <strong>Acknowledged</strong> before you can continue.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-allergy-confirm.png" alt="A2 kiosk allergy confirm" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">This step matters. Your acknowledgment is recorded, which is what protects everyone if a child has a reaction later. Don&apos;t skip past it.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Choosing who can pick up</h3>
      <p className="mt-3">Ask the parent, &quot;Who will be picking up today?&quot; Tap each adult or authorized contact who&apos;ll be there at pickup.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-recipient-selection.png" alt="A2 kiosk recipient selection" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">The security-code text message goes to everyone you select, plus the primary guardian automatically. This is how a grandparent doing pickup gets the code on their own phone.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The success screen and the security code</h3>
      <p className="mt-3">A 4-character security code appears.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-success-with-code.png" alt="A2 kiosk success with code" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">If a label printer is set up, the kiosk also prints the labels automatically: one large name tag per child, plus one guardian receipt showing the security code. The kiosk resets itself after 30 seconds.</p>
      <p className="mt-3"><strong>What the code is for:</strong> it&apos;s the release authorization. When the parent comes back, the volunteer at a staffed kiosk asks for the code &mdash; from their text message or printed receipt &mdash; and matches it to the code on the child&apos;s name tag. A match means the child is released.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The &quot;I&apos;m here for pickup&quot; button</h3>
      <p className="mt-3">On the child-selection screen, next to <strong>Next</strong>, there&apos;s a sage-green <strong>I&apos;m here for pickup</strong> button.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-pickup-ready-button-visible.png" alt="A2 kiosk pickup ready button visible" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">This is for a parent who isn&apos;t checking in &mdash; they&apos;re arriving to collect their child. Tapping it sends a ping to the teacher&apos;s dashboard so they can bring the child to the lobby. It does not release the child on its own; the security code at a staffed kiosk is still the actual release step.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">If something doesn&apos;t go as expected</h3>
      <p className="mt-3"><strong>&quot;I scanned the QR but nothing happened.&quot;</strong> Try better lighting on the code, or fall back to the last 4 digits of the phone.</p>
      <p className="mt-3"><strong>&quot;What do I do about the Pickup note badge?&quot;</strong> Nothing at check-in. The full details come up automatically at checkout.</p>
      <p className="mt-3"><strong>&quot;The pass scanned but showed the wrong family.&quot;</strong> Unusual &mdash; re-scan. If it keeps happening, the family may have an old pass that was generated for a different household.</p>
      <p className="mt-3"><strong>&quot;Do I have to print labels?&quot;</strong> Only if your church has the printer set up. The security code is the real gate; labels are a convenience.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Messages you might see</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>&quot;Household not found&quot;</strong> &mdash; try the next lookup method, or tap <strong>New family</strong></li>
        <li className="mt-1"><strong>&quot;Allergy data load failed&quot;</strong> &mdash; select fewer children and try again. Don&apos;t skip the alert step</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A1 &mdash; First-time kiosk setup</strong></li>
        <li className="mt-1"><strong>B1 &mdash; Apple Wallet family pass</strong> (for parents)</li>
        <li className="mt-1"><strong>B2 &mdash; Parent-arrival pickup ping</strong> (the &quot;I&apos;m here for pickup&quot; path)</li>
        <li className="mt-1"><strong>Label printing</strong></li>
        <li className="mt-1"><strong>Registering households</strong></li>
      </ul>
      </>
    ),
  },
  // a3-teacher-view — tier 1
  {
    slug: "a3-teacher-view",
    title: "The teacher view on your phone",
    tier: 1,
    content: (
      <>
      <p className="mt-3">This is the page you pull up when you need to know who&apos;s in your room, check a child&apos;s alerts, reach a parent, or respond to a parent who&apos;s arrived for pickup. It&apos;s built to be glanced at quickly.</p>
      <p className="mt-3"><strong>Before you start:</strong> check yourself into the room at the kiosk first. This view only shows rooms you&apos;re checked into. (Your church also needs to be on Growth tier or above.)</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Getting to your room</h3>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">From the dashboard sidebar, tap <strong>Check-In</strong></li>
        <li className="mt-1">On the Check-In page, tap the <strong>Teacher View</strong> tile under Quick Actions</li>
      </ol>
      <p className="mt-3">You&apos;ll land on your rooms.</p>
      <figure className="my-4"><Image src="/help/checkin/a3-checkin-quickactions-with-teacher-view.png" alt="A3 checkin quickactions with teacher view" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">If you haven&apos;t checked into a room yet, you&apos;ll see an empty state pointing you back to the kiosk.</p>
      <figure className="my-4"><Image src="/help/checkin/a3-teacher-view-empty-state.png" alt="A3 teacher view empty state" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What the page shows</h3>
      <p className="mt-3">Each room you&apos;re checked into appears as its own section with:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">The room name and total number of children</li>
        <li className="mt-1">A ratio status indicator &mdash; <strong>OK</strong>, <strong>Warning</strong>, or <strong>Violation</strong> &mdash; based on your church&apos;s children-to-adult ratio policy</li>
        <li className="mt-1">The list of children in the room</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a3-teacher-view-with-children.png" alt="A3 teacher view with children" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3"><strong>Each child&apos;s row shows:</strong></p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Name and grade</li>
        <li className="mt-1">An allergy badge if they have one, plus their allergies, medications, and medical notes (your church decides which of these show directly and which you tap to reveal)</li>
        <li className="mt-1">The parent&apos;s phone number, masked for privacy as <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">***1234</code></li>
        <li className="mt-1">A <strong>Page parent</strong> button (the coral button on the row) for sending a quick text &mdash; see the <strong>B3</strong> guide</li>
        <li className="mt-1">When a parent has arrived: a coral background and ring, a <strong>Parent here for pickup</strong> header, and an <strong>On my way</strong> button &mdash; see the <strong>B2</strong> guide</li>
        <li className="mt-1">When attendance is being taken: <strong>Present</strong> and <strong>Not in room</strong> pills below the parent line &mdash; see the <strong>B5</strong> guide</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Staying current</h3>
      <p className="mt-3">The page refreshes itself every 30 seconds while it&apos;s open. If your phone screen goes to sleep, it pauses to save battery and picks back up when you wake it. You can also pull down to refresh.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Leaving your room</h3>
      <p className="mt-3">When you&apos;re done, check yourself out at the kiosk (or through the usual volunteer checkout). After you check out, this page stops showing your roster.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">If something doesn&apos;t look right</h3>
      <p className="mt-3"><strong>&quot;Why is the phone number masked?&quot;</strong> Privacy. You don&apos;t need to dial it directly &mdash; tap <strong>Page parent</strong> to text them instead.</p>
      <p className="mt-3"><strong>&quot;I see a coral row but no buttons.&quot;</strong> You may not be checked in. Re-check yourself in at the kiosk.</p>
      <p className="mt-3"><strong>&quot;I don&apos;t see the room across the hall.&quot;</strong> This view only shows rooms you&apos;re checked into. Each volunteer sees their own assignments.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Messages you might see</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>&quot;You&apos;re not checked in to any rooms&quot;</strong> &mdash; head to the kiosk and check in first</li>
        <li className="mt-1">Data looks a few seconds stale &mdash; pull down to refresh, or wait for the next 30-second cycle</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a3-teacher-view-pickup-ready-state.png" alt="A3 teacher view pickup ready state" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/a3-teacher-view-acknowledged-state.png" alt="A3 teacher view acknowledged state" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/a3-page-parent-modal.png" alt="A3 page parent modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A1 &mdash; First-time kiosk setup</strong></li>
        <li className="mt-1"><strong>B2 &mdash; Parent-arrival pickup ping</strong> (the other side of it)</li>
        <li className="mt-1"><strong>B3 &mdash; Page Parent text</strong> (full details)</li>
        <li className="mt-1"><strong>B5 &mdash; Attendance pills</strong> (full details)</li>
      </ul>
      </>
    ),
  },
  // a4-admin-room-view — tier 1
  {
    slug: "a4-admin-room-view",
    title: "Checking on a room from the admin dashboard",
    tier: 1,
    content: (
      <>
      <p className="mt-3">This is how you keep an eye on the whole building during a service &mdash; see how full each room is, who&apos;s staffing it, and reach a parent if you need to. You can do it from a laptop or from an iPad as you walk around.</p>
      <p className="mt-3"><strong>Before you start:</strong> you&apos;ll need an admin or owner role, and today&apos;s services need to be underway.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Where you start</h3>
      <p className="mt-3">Open <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">/dashboard/checkin</code> for the live Check-In dashboard. It shows:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Total children checked in today</li>
        <li className="mt-1">A breakdown bar for each room, showing children in vs. capacity, with a color that tells you fullness at a glance: <strong>sage</strong> under 80%, <strong>amber</strong> 80&ndash;99%, <strong>coral</strong> at 100% or over</li>
        <li className="mt-1">Recent check-in activity</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a4-checkin-dashboard-with-clickable-rooms.png" alt="A4 checkin dashboard with clickable rooms" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Drilling into a room</h3>
      <p className="mt-3">Each room card is clickable. Tapping one opens that room&apos;s view for today.</p>
      <figure className="my-4"><Image src="/help/checkin/a4-room-drilldown-typical.png" alt="A4 room drilldown typical" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">The room page shows:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">The room name and capacity</li>
        <li className="mt-1">Totals: children present, adults on duty, children checked out</li>
        <li className="mt-1"><strong>Adults on duty</strong> &mdash; every volunteer checked into the room, with the time they checked in. <strong>If this section is empty, a warning banner appears</strong> &mdash; your ratio policy is at risk</li>
        <li className="mt-1"><strong>Children present</strong> &mdash; each child&apos;s name, grade, and check-in time, the parent&apos;s name, and a tappable phone number. As an admin you see the full, unmasked number (the masking volunteers see doesn&apos;t apply to you). Medical alerts show a badge and the full details</li>
      </ul>
      <p className="mt-3">The page refreshes every 30 seconds.</p>
      <figure className="my-4"><Image src="/help/checkin/a4-room-drilldown-with-medical-alerts.png" alt="A4 room drilldown with medical alerts" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">When &quot;Adults on duty&quot; is empty</h3>
      <figure className="my-4"><Image src="/help/checkin/a4-room-drilldown-no-adults-warning.png" alt="A4 room drilldown no adults warning" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">It means one of two things: a volunteer is in the room but forgot to check themselves in at the kiosk, or no one is actually there. Walk over and confirm. Then either re-check the volunteer in at the kiosk, or assign a backup.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Getting around</h3>
      <p className="mt-3">A back link returns you to <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">/dashboard/checkin</code>. On a phone, the parent&apos;s phone number is tappable &mdash; tap it to dial.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">A note on permissions</h3>
      <p className="mt-3">Only admin and owner roles can open this page. For an iPad mounted on the wall inside a classroom, use the wall-display view instead (<code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">/checkin/room/...</code> with its token) &mdash; that&apos;s the surface built for that job.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">If the numbers don&apos;t match what you see</h3>
      <p className="mt-3"><strong>&quot;The room shows 3 children but the volunteer says 4 are here.&quot;</strong> The count is based on kiosk check-ins. A child standing in the room who never got checked in won&apos;t appear. Walk to the kiosk and check them in.</p>
      <p className="mt-3"><strong>&quot;The room shows 0 capacity.&quot;</strong> Capacity is set in <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">Settings → Check-In → Rooms</code>. Give it a real number so the ratio bars work.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Messages you might see</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>&quot;Room not found&quot;</strong> &mdash; the link is stale or the room was deleted</li>
        <li className="mt-1"><strong>&quot;Admin or owner role required&quot;</strong> &mdash; volunteers without that role don&apos;t see this page</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A5 &mdash; Emergency / first-responder roster</strong> (when you need the cross-room view)</li>
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong> (where this data comes from)</li>
        <li className="mt-1"><strong>Volunteer ratio policy</strong></li>
      </ul>
      </>
    ),
  },
  // a5-emergency-roster — tier 1
  {
    slug: "a5-emergency-roster",
    title: "The emergency roster",
    tier: 1,
    content: (
      <>
      <p className="mt-3">The emergency roster is the single view that gives you everything you need in an actual emergency &mdash; a fire drill, an evacuation, a missing child. It lists every checked-in child across all rooms, with full medical and contact information, and prints cleanly for a first responder.</p>
      <p className="mt-3"><strong>Before you start:</strong> you&apos;ll need an admin or owner role, and there need to be children currently checked in.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What it&apos;s for</h3>
      <p className="mt-3">This view shows complete medical information for every child, regardless of the visibility settings that normally limit what staff can see. That&apos;s deliberate: an EMT or an evacuation marshal needs the full picture, immediately, with nothing held back.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Every access is recorded</h3>
      <p className="mt-3">Each time someone opens this page, the system records it along with any reason given. This isn&apos;t punitive. It exists so your church leadership can match each access to a real incident afterward.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Getting there</h3>
      <p className="mt-3">From <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">/dashboard/checkin</code>, tap the <strong>Emergency Roster</strong> tile. The tile is visible only to admin and owner roles.</p>
      <figure className="my-4"><Image src="/help/checkin/a5-emergency-tile-admin-view.png" alt="A5 emergency tile admin view" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">On first open, a short confirmation appears with an optional reason field &mdash; for example, &quot;Fire drill&quot; or &quot;Missing child report.&quot; Whatever you enter is saved with the access record. Tap <strong>Open roster</strong> to continue.</p>
      <figure className="my-4"><Image src="/help/checkin/a5-consent-modal.png" alt="A5 consent modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What the roster shows</h3>
      <p className="mt-3">Children are grouped by room. Each row includes:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Name, grade, and a checkbox to mark the child as accounted for (this is just for your own head count as you confirm children)</li>
        <li className="mt-1">An <strong>ALERT</strong> badge if any medical information is on file</li>
        <li className="mt-1">A bold amber <strong>REPORTED ABSENT FROM ROOM</strong> badge if a teacher has marked the child as not actually in the room</li>
        <li className="mt-1">A subtle sage <strong>Confirmed present</strong> badge if a teacher has marked them present</li>
        <li className="mt-1">Full allergies, medications, and medical notes</li>
        <li className="mt-1">The parent&apos;s name and full phone number</li>
        <li className="mt-1">Every authorized pickup contact &mdash; name, relationship, and phone</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a5-roster-typical.png" alt="A5 roster typical" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/a5-roster-with-reported-absent-badge.png" alt="A5 roster with reported absent badge" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What &quot;Reported absent from room&quot; means</h3>
      <p className="mt-3">A teacher has indicated the child was checked in but isn&apos;t physically in their room. For a marshal, that means: don&apos;t spend search time looking in that room. Check elsewhere &mdash; a bathroom, the lobby, the parking lot.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Printing a copy</h3>
      <p className="mt-3">Tap the print button (or use your browser&apos;s File → Print). The printed version is built for paper and monochrome: it drops the navigation, lays each child out for a standard page, and converts the badges into bordered black-and-white shapes that stay readable. Hand the printout to the marshal or the EMT.</p>
      <figure className="my-4"><Image src="/help/checkin/a5-roster-print-preview.png" alt="A5 roster print preview" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Things to know</h3>
      <p className="mt-3"><strong>It shows fewer children than expected.</strong> Only children currently checked in appear. Any who&apos;ve already been checked out drop off. To account for everyone who was in the building today, including those who left, use the history on the regular Check-In dashboard.</p>
      <p className="mt-3"><strong>Can I use it on a phone?</strong> Yes. The screen view works on mobile; the print layout is the part optimized for paper.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Messages you might see</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>&quot;Admin or owner role required&quot;</strong> &mdash; the tile is hidden for other roles, and opening the link directly is blocked</li>
        <li className="mt-1">A <strong>&quot;Data load failed&quot;</strong> row inside the roster &mdash; one child or household record didn&apos;t load. The row still shows the session ID and room, so a marshal knows to ask the kiosk operator for that child</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A4 &mdash; Admin per-room drill-down</strong> (for routine monitoring)</li>
        <li className="mt-1"><strong>B5 &mdash; Attendance-taking</strong> (how the absent flag gets set)</li>
        <li className="mt-1"><strong>Audit log access</strong></li>
      </ul>
      </>
    ),
  },
  // b1-apple-wallet-pass — tier 2
  {
    slug: "b1-apple-wallet-pass",
    title: "Adding your family's check-in pass to Apple Wallet",
    tier: 2,
    content: (
      <>
      <p className="mt-3">The check-in pass is a quick way to identify your family at the kiosk &mdash; no typing a phone number or carrying a printed card. This guide gets it onto your iPhone and explains the one bit of &quot;how does it know?&quot; magic.</p>
      <p className="mt-3"><strong>Before you start:</strong> your church needs to have you registered as a guardian, and you&apos;ll need an iPhone. (An Android version is on the way but isn&apos;t available yet.)</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What the pass is</h3>
      <p className="mt-3">It&apos;s a permanent ID for your household. At the kiosk, you hold it up to scan instead of entering the last four digits of your phone or scanning a printed QR card.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Adding it</h3>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">Open the guardian portal link your church sent you</li>
        <li className="mt-1">Tap <strong>Add to Apple Wallet</strong></li>
        <li className="mt-1">Tap <strong>Add</strong> on the screen iOS shows you</li>
      </ol>
      <figure className="my-4"><Image src="/help/checkin/b1-guardian-portal-add-button.png" alt="B1 guardian portal add button" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <div className="my-4 rounded-lg border-2 border-dashed border-vc-border bg-vc-bg-warm/40 p-4 text-sm text-vc-text-muted"><strong>Screenshot pending:</strong> <code>b1-ios-wallet-add-sheet</code> &mdash; see <code>docs/help-guides/checkin/inbox-codex/SKIPPED.md</code></div>
      <p className="mt-3">That&apos;s it &mdash; the pass now lives in your Wallet.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The location-aware part</h3>
      <p className="mt-3">When your iPhone notices you&apos;re within about 100 meters of the church, the pass surfaces on your lock screen with &quot;Check in at&quot; and your campus name. One tap opens it in Wallet, ready to scan. You don&apos;t have to go hunting for it.</p>
      <div className="my-4 rounded-lg border-2 border-dashed border-vc-border bg-vc-bg-warm/40 p-4 text-sm text-vc-text-muted"><strong>Screenshot pending:</strong> <code>b1-pass-on-lock-screen-near-church</code> &mdash; see <code>docs/help-guides/checkin/inbox-codex/SKIPPED.md</code></div>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What&apos;s on the pass</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Your family name</li>
        <li className="mt-1">Your children&apos;s first names</li>
        <li className="mt-1">A household barcode the kiosk reads</li>
        <li className="mt-1">Your church&apos;s logo, if they&apos;ve uploaded one</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">A note on the security code</h3>
      <p className="mt-3">The 4-character pickup code is <strong>not</strong> on the pass. That code changes with every check-in and is sent to you separately by text. The two do different jobs: the pass identifies your household, and the code authorizes releasing your child.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Keeping it up to date</h3>
      <p className="mt-3">For now, the pass is a snapshot from when you added it. If your family name changes or a new child joins, open the guardian portal again and tap <strong>Add to Apple Wallet</strong> to refresh it. (Automatic updates are a planned improvement.)</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong> (the pass-scan path at check-in)</li>
      </ul>
      </>
    ),
  },
  // b2-pickup-ready-ping — tier 2
  {
    slug: "b2-pickup-ready-ping",
    title: "Letting the room know you're here for pickup",
    tier: 2,
    content: (
      <>
      <p className="mt-3">When the children&apos;s area is secured and parents can&apos;t walk back to the classroom, this lets a parent signal the room from the lobby &mdash; and lets the teacher respond. This guide has a section for each side.</p>
      <hr className="my-6 border-vc-border-light" />
      <p className="mt-3">## For parents</p>
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Why this exists</h3>
      <p className="mt-3">If the children&apos;s-ministry area is behind a locked door, you can&apos;t just walk to the classroom to collect your child. Instead of finding a staff member to radio the room, you send the signal yourself from the kiosk.</p>
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What to do</h3>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">Walk up to the kiosk and find your household (any lookup method works)</li>
        <li className="mt-1">Tap <strong>I&apos;m here for pickup</strong> &mdash; the sage-green button on the child-selection screen, above <strong>Back</strong> and <strong>Next</strong></li>
        <li className="mt-1">Wait in the lobby with your pickup code ready</li>
      </ol>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-pickup-ready-button-visible.png" alt="A2 kiosk pickup ready button visible" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/b2-kiosk-pickup-ready-success.png" alt="B2 kiosk pickup ready success" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">One thing to know</h3>
      <p className="mt-3">This is just a heads-up to the room &mdash; it doesn&apos;t release your child on its own. At the kiosk, the volunteer still matches your security code to the code on your child&apos;s name tag before handing them over. Have the code ready.</p>
      <hr className="my-6 border-vc-border-light" />
      <p className="mt-3">## For teachers</p>
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Seeing the signal</h3>
      <p className="mt-3">Your teacher dashboard refreshes every 30 seconds. When a parent sends the signal, that child&apos;s row changes to a coral background with a coral ring and a header reading <strong>Parent here for pickup</strong>. A sage-green <strong>On my way</strong> button appears at the start of the row&apos;s buttons.</p>
      <figure className="my-4"><Image src="/help/checkin/a3-teacher-view-pickup-ready-state.png" alt="A3 teacher view pickup ready state" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Responding</h3>
      <p className="mt-3">Tap <strong>On my way</strong>. The row flips to a sage <strong>Acknowledged</strong> state, which tells the other teachers &mdash; and any admin watching the room view &mdash; that someone&apos;s handling it. Then walk the child to the lobby and go through the normal checkout.</p>
      <figure className="my-4"><Image src="/help/checkin/a3-teacher-view-acknowledged-state.png" alt="A3 teacher view acknowledged state" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">If something doesn&apos;t go as expected</h3>
      <p className="mt-3"><strong>(Parent) &quot;I sent it but no one came.&quot;</strong> The teacher may not have acknowledged yet &mdash; the row updates within 30 seconds. If there&apos;s still no response after a few minutes, find a staff member.</p>
      <p className="mt-3"><strong>(Teacher) &quot;Another teacher and I both tapped On my way.&quot;</strong> That&apos;s fine. The latest tap wins, and both phones show the same acknowledged state on the next refresh.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong></li>
        <li className="mt-1"><strong>A3 &mdash; The teacher view</strong></li>
      </ul>
      </>
    ),
  },
  // b3-page-parent — tier 2
  {
    slug: "b3-page-parent",
    title: "Texting a parent from your room",
    tier: 2,
    content: (
      <>
      <p className="mt-3">When you need to reach a parent about something that isn&apos;t an emergency, <strong>Page parent</strong> sends them a quick text without you leaving the room or dialing a number.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">When to use it</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">A child is asking for their parent</li>
        <li className="mt-1">A child needs a diaper change and you&apos;re out of supplies</li>
        <li className="mt-1">A child is feeling unwell &mdash; but not seriously. For anything urgent or medical, find a staff member rather than texting</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">How it works</h3>
      <p className="mt-3">Each child&apos;s row on the teacher dashboard has a coral <strong>Page parent</strong> button.</p>
      <figure className="my-4"><Image src="/help/checkin/b3-page-parent-button.png" alt="B3 page parent button" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">Tap it to open a short form with an optional note (up to 200 characters). A note helps the parent know what&apos;s going on before they get to you. Useful examples:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">&quot;Aria is asking for you &mdash; could you stop by Room 3?&quot;</li>
        <li className="mt-1">&quot;Eli could use a diaper change and we&apos;re out of his size.&quot;</li>
        <li className="mt-1">&quot;Noah&apos;s a little under the weather and would like you.&quot;</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a3-page-parent-modal.png" alt="A3 page parent modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Who gets the text</h3>
      <p className="mt-3">The text goes to the primary guardian and to every authorized contact the parent chose at check-in. If two of those contacts share a phone number, they only get one message.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The 60-second cooldown</h3>
      <p className="mt-3">After you page a parent, the button pauses for 60 seconds for that child before you can page them again. This keeps a repeated tap from sending a string of texts.</p>
      <figure className="my-4"><Image src="/help/checkin/b3-page-parent-cooldown-state.png" alt="B3 page parent cooldown state" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What the parent receives</h3>
      <p className="mt-3">The text identifies your church and room and includes your note. For example:</p>
      <p className="mt-3">&gt; Anchor Falls Check-In: A volunteer in Room 3 would like to reach you about Aria. &quot;Aria is asking for you &mdash; could you stop by?&quot;</p>
      <p className="mt-3"><em>(Wording shown is an example &mdash; confirm the exact message template with your VolunteerCal setup.)</em></p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A3 &mdash; The teacher view</strong></li>
      </ul>
      </>
    ),
  },
  // b4-blocked-pickup — tier 2
  {
    slug: "b4-blocked-pickup",
    title: "Blocked-pickup entries and checkout verification",
    tier: 2,
    content: (
      <>
      <p className="mt-3">Some households have a person who must not pick up a child &mdash; often under a court order. VolunteerCal records these privately and surfaces them to the kiosk operator at checkout. This guide covers adding an entry (for admins) and verifying at checkout (for volunteers). Every action described here is recorded in the audit log.</p>
      <hr className="my-6 border-vc-border-light" />
      <p className="mt-3">## For admins: adding an entry</p>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">Open the household&apos;s detail page and scroll to the <strong>Not authorized for pickup</strong> section</li>
        <li className="mt-1">Tap <strong>Add entry</strong></li>
      </ol>
      <figure className="my-4"><Image src="/help/checkin/b4-household-detail-pickup-sections.png" alt="B4 household detail pickup sections" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">The entry has these fields:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Name</strong> and <strong>phone</strong> of the person not authorized</li>
        <li className="mt-1"><strong>Scope</strong> &mdash; child or household. Household scope applies the restriction to every sibling, which is appropriate when a court order covers them all</li>
        <li className="mt-1"><strong>Reason</strong> &mdash; court order, household decision, or other</li>
        <li className="mt-1"><strong>Photo</strong> (optional) &mdash; a photo of the person</li>
        <li className="mt-1"><strong>Supporting document</strong> (optional) &mdash; for example, a PDF of the court order</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/b4-add-blocked-modal.png" alt="B4 add blocked modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">Photos are stored privately and are visible only to kiosk operators, and only at the checkout-confirmation step. To change or remove an entry, edit it the same way. Both additions and removals are recorded in the audit log.</p>
      <hr className="my-6 border-vc-border-light" />
      <p className="mt-3">## For kiosk operators: verifying at checkout</p>
      <p className="mt-3"><strong>At check-in:</strong> the child&apos;s card shows a small amber <strong>Pickup note</strong> badge with a lock icon. It&apos;s intentionally discreet so a child glancing at the screen won&apos;t see any details. It only means there&apos;s something on file that the system will handle at checkout.</p>
      <figure className="my-4"><Image src="/help/checkin/a2-kiosk-child-selection-with-badges.png" alt="A2 kiosk child selection with badges" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3"><strong>At checkout:</strong> the kiosk shows a full-screen review with every blocked-pickup entry for the household &mdash; photos, names, and reasons. Compare the person standing in front of you to the photo.</p>
      <figure className="my-4"><Image src="/help/checkin/b4-kiosk-blocked-review-modal.png" alt="B4 kiosk blocked review modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>If you recognize the person as someone on the list,</strong> tap <strong>Person IS on this list</strong>. This alerts the church&apos;s Emergency Response Team by text and does not release the child</li>
        <li className="mt-1"><strong>If the person is not on the list,</strong> tap <strong>Confirm &mdash; not on the list</strong>. The child continues to the normal security-code checkout</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Policy notes</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">This check is only as strong as the entries behind it. An entry with a photo can be verified; a name-only entry is much harder to act on</li>
        <li className="mt-1">If you aren&apos;t certain the person matches the photo, find another staff member. Never release a child when there&apos;s doubt</li>
        <li className="mt-1">Self-service kiosks cannot clear a blocked-pickup entry. A household with a blocked entry must check out at a staffed kiosk</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong></li>
        <li className="mt-1"><strong>A5 &mdash; Emergency / first-responder roster</strong></li>
      </ul>
      </>
    ),
  },
  // b5-attendance-taking — tier 2
  {
    slug: "b5-attendance-taking",
    title: "Marking who's actually in your room",
    tier: 2,
    content: (
      <>
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Why this matters</h3>
      <p className="mt-3">A child can be checked in at the kiosk but not physically in your room &mdash; they wandered off with a sibling, they&apos;re in the bathroom, they slipped out. In an emergency, the evacuation marshal or EMT needs to know that, so they don&apos;t waste time searching your room for a child who isn&apos;t there. Marking attendance is how that information reaches them.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The two pills</h3>
      <p className="mt-3">Each child&apos;s row on the teacher dashboard has two pills:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Present</strong> &mdash; sage when active</li>
        <li className="mt-1"><strong>Not in room</strong> &mdash; amber when active</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/b5-attendance-pills-unmarked.png" alt="B5 attendance pills unmarked" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">Tap a pill to set it. Tap the active pill again to clear it back to unmarked. The two are independent, but only one can be active at a time &mdash; the system enforces that for you.</p>
      <figure className="my-4"><Image src="/help/checkin/b5-attendance-pills-present.png" alt="B5 attendance pills present" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/b5-attendance-pills-not-in-room.png" alt="B5 attendance pills not in room" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">If two teachers in the same room mark the same child differently within about 30 seconds, the most recent mark wins.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">When to mark each one</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Present</strong> &mdash; once you&apos;ve physically counted the child in your room</li>
        <li className="mt-1"><strong>Not in room</strong> &mdash; when a child was checked in at the kiosk but hasn&apos;t actually appeared in your space</li>
        <li className="mt-1"><strong>Clear it</strong> &mdash; when a child you&apos;d marked absent shows up</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Where it shows up</h3>
      <p className="mt-3">Your marks flow straight to the emergency roster:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Not in room</strong> becomes a bold amber <strong>REPORTED ABSENT FROM ROOM</strong> badge</li>
        <li className="mt-1"><strong>Present</strong> becomes a subtle sage <strong>Confirmed present</strong> badge</li>
        <li className="mt-1">Unmarked children show no badge</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/a5-roster-with-reported-absent-badge.png" alt="A5 roster with reported absent badge" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A3 &mdash; The teacher view</strong></li>
        <li className="mt-1"><strong>A5 &mdash; Emergency / first-responder roster</strong></li>
      </ul>
      </>
    ),
  },
  // c1-edit-household — tier 3
  {
    slug: "c1-edit-household",
    title: "Editing a household",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Admin or coordinator keeping household records current.</p>
      <p className="mt-3"><strong>Outcome:</strong> You can update guardian details, add a child, and change a child&apos;s grade or default room.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Editing guardian information</h3>
      <p className="mt-3">Open the household&apos;s detail page and edit the primary or secondary guardian&apos;s information &mdash; name, phone, and contact details.</p>
      <figure className="my-4"><Image src="/help/checkin/c1-household-edit-modal.png" alt="C1 household edit modal" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Adding a child</h3>
      <p className="mt-3">From the household page, add a child and fill in their name, grade, and default room. They&apos;ll be available to check in right away.</p>
      <figure className="my-4"><Image src="/help/checkin/c1-child-add-confirm.png" alt="C1 child add confirm" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Changing grade or default room</h3>
      <p className="mt-3">Update a child&apos;s grade or default room from their entry on the household page. The new room is what the kiosk will auto-assign at the next check-in.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong></li>
        <li className="mt-1"><strong>C2 &mdash; Annual grade roll-up</strong></li>
      </ul>
      </>
    ),
  },
  // c2-grade-rollup — tier 3
  {
    slug: "c2-grade-rollup",
    title: "Annual grade roll-up",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Admin doing the start-of-year update.</p>
      <p className="mt-3"><strong>Outcome:</strong> Every child&apos;s grade advances to the new school year.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The manual process (current)</h3>
      <p className="mt-3">Until an automated tool is confirmed, roll grades up in three steps:</p>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Export</strong> your household and child records</li>
        <li className="mt-1"><strong>Edit</strong> the grade column &mdash; advance each child to their new grade, and remove any who have aged out of children&apos;s ministry</li>
        <li className="mt-1"><strong>Import</strong> the updated file back in</li>
      </ol>
      <p className="mt-3">Spot-check a handful of children afterward to confirm grades and default rooms came across correctly.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Feature request on file</h3>
      <p className="mt-3">An automated, one-click grade roll-up &mdash; &quot;advance everyone one grade, with a preview and an undo&quot; &mdash; would remove the export/edit/import round trip entirely. This is flagged as a future enhancement.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>C1 &mdash; Editing a household</strong> (for one-off grade changes)</li>
      </ul>
      </>
    ),
  },
  // c3-visitor-registration — tier 3
  {
    slug: "c3-visitor-registration",
    title: "Registering a first-time family at the kiosk",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Volunteer at the kiosk, or an admin helping a new family.</p>
      <p className="mt-3"><strong>Outcome:</strong> A visiting family is registered and checked in, on the spot, in under a minute.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The flow</h3>
      <ol className="list-decimal pl-6 mt-3 space-y-1">
        <li className="mt-1">On the kiosk start screen, tap <strong>New family</strong></li>
        <li className="mt-1">Enter the guardian&apos;s information &mdash; name and phone</li>
        <li className="mt-1">Add each child &mdash; name, grade, and any allergy or medical notes</li>
        <li className="mt-1">Review the details, then continue into the normal check-in (selecting children, acknowledging any alerts, choosing who can pick up)</li>
      </ol>
      <figure className="my-4"><Image src="/help/checkin/c3-visitor-new-family-button.png" alt="C3 visitor new family button" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/c3-visitor-guardian-info.png" alt="C3 visitor guardian info" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/c3-visitor-add-children.png" alt="C3 visitor add children" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <figure className="my-4"><Image src="/help/checkin/c3-visitor-review.png" alt="C3 visitor review" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">The new household is saved, so next time the family can be found by phone, QR card, or Apple Wallet pass like anyone else.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong></li>
        <li className="mt-1"><strong>C1 &mdash; Editing a household</strong> (to fill in details later)</li>
      </ul>
      </>
    ),
  },
  // c4-multi-campus — tier 3
  {
    slug: "c4-multi-campus",
    title: "Multi-campus check-in",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Admin at a church running more than one campus.</p>
      <p className="mt-3"><strong>Outcome:</strong> You understand how rooms, services, and passes behave per campus.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The campus selector</h3>
      <p className="mt-3">When your church has more than one campus, a campus selector lets you choose which one you&apos;re working in. Rooms and services are set up per campus, so what you see follows the campus you&apos;ve selected.</p>
      <figure className="my-4"><Image src="/help/checkin/c4-campus-selector.png" alt="C4 campus selector" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Per-campus rooms and services</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Rooms</strong> are configured separately for each campus &mdash; a room at one campus doesn&apos;t appear at another</li>
        <li className="mt-1"><strong>Service times</strong> are also per campus, so each location can run its own schedule</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/c4-per-campus-rooms.png" alt="C4 per campus rooms" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Apple Wallet passes across campuses</h3>
      <p className="mt-3">The location-aware pass works at any campus you&apos;ve set GPS coordinates for. When a family is near that campus, their pass surfaces with that campus&apos;s name. Make sure each campus has its coordinates set so the lock-screen prompt fires.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A1 &mdash; First-time kiosk setup</strong> (stations are bound per church)</li>
        <li className="mt-1"><strong>B1 &mdash; Apple Wallet family pass</strong> (the location-aware behavior)</li>
      </ul>
      </>
    ),
  },
  // c5-recovery-scenarios — tier 3
  {
    slug: "c5-recovery-scenarios",
    title: "Recovery scenarios at pickup",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Admin handling the situations that don&apos;t fit the normal flow.</p>
      <p className="mt-3"><strong>Outcome:</strong> You can release a child safely when the code or phone is missing, or when a different guardian arrives.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The parent doesn&apos;t have their security code</h3>
      <p className="mt-3">Look up the child&apos;s session in the admin tools &mdash; you can surface the security code from there and confirm it against the child&apos;s name tag.</p>
      <figure className="my-4"><Image src="/help/checkin/c5-session-lookup-code.png" alt="C5 session lookup code" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">The parent can&apos;t get their text</h3>
      <p className="mt-3">If the code never reached the parent&apos;s phone, verify their identity another way &mdash; a driver&apos;s license, for instance &mdash; and release the child once you&apos;re satisfied.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">A second guardian arrives instead of the one who checked in</h3>
      <p className="mt-3">The authorized pickup list governs. If the person arriving is on that household&apos;s authorized list, they can collect the child. If they aren&apos;t, don&apos;t release until you&apos;ve confirmed they&apos;re authorized.</p>
      <figure className="my-4"><Image src="/help/checkin/c5-authorized-pickup-list.png" alt="C5 authorized pickup list" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong> (security codes and recipients)</li>
        <li className="mt-1"><strong>B4 &mdash; Blocked-pickup entries</strong> (when someone must not pick up)</li>
        <li className="mt-1"><strong>C6 &mdash; Parent self-service</strong></li>
      </ul>
      </>
    ),
  },
  // c6-parent-self-service — tier 3
  {
    slug: "c6-parent-self-service",
    title: "Managing your pickups and finding your code",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Parent / guardian.</p>
      <p className="mt-3"><strong>Outcome:</strong> You can manage who&apos;s allowed to pick up your child, and find your security code if the text doesn&apos;t arrive.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Authorized pickup contacts</h3>
      <p className="mt-3">From your family pickups page (<code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded">/dashboard/account/family/pickups</code>), you can add an authorized pickup contact or request that one be removed.</p>
      <figure className="my-4"><Image src="/help/checkin/c6-pickups-page.png" alt="C6 pickups page" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">When you add a contact, every guardian on the household is notified, and the change is recorded in the audit log &mdash; so there&apos;s always a clear record of who can pick up and when that changed.</p>
      <figure className="my-4"><Image src="/help/checkin/c6-add-pickup-contact.png" alt="C6 add pickup contact" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Finding your security code</h3>
      <p className="mt-3">If the security-code text doesn&apos;t reach you, you can view the code on your phone from your account rather than waiting on the message. Have it ready at the kiosk so the volunteer can match it to your child&apos;s name tag.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A2 &mdash; Running the kiosk</strong> (how the code is used)</li>
        <li className="mt-1"><strong>C5 &mdash; Recovery scenarios</strong> (what the admin can do if you&apos;re stuck)</li>
      </ul>
      </>
    ),
  },
  // c7-checkin-scheduling — tier 3
  {
    slug: "c7-checkin-scheduling",
    title: "Scheduling volunteers for check-in rooms",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Admin or coordinator planning who staffs which room.</p>
      <p className="mt-3"><strong>Outcome:</strong> Teachers and aides are assigned to specific rooms for a service, so the ratio works out before Sunday.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Assigning a room for a service</h3>
      <p className="mt-3">For a given service, assign teachers and aides to the rooms they&apos;ll cover. Planning assignments ahead of time means each room has enough adults to meet your ratio policy when families start arriving.</p>
      <figure className="my-4"><Image src="/help/checkin/c7-room-assignments.png" alt="C7 room assignments" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <p className="mt-3">A scheduled assignment is the plan. The live ratio on Sunday still reflects who has actually <strong>checked into</strong> the room at the kiosk &mdash; so remind volunteers that checking in at the kiosk is what makes them count toward the room (see <strong>A3</strong>).</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Where this connects</h3>
      <p className="mt-3">Check-in room assignments use VolunteerCal&apos;s broader scheduling tools. For building schedules, handling availability, and sending reminders, see the volunteer scheduling documentation.</p>
      <p className="mt-3">&gt; <strong>Author note:</strong> this guide leans on the existing scheduling docs, which &gt; weren&apos;t in the brief. Confirm the exact assignment path and any &gt; check-in-specific scheduling screens before publishing.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A3 &mdash; The teacher view</strong> (checking into an assigned room)</li>
        <li className="mt-1"><strong>A4 &mdash; Admin per-room drill-down</strong> (seeing live staffing and gaps)</li>
        <li className="mt-1">Volunteer scheduling documentation</li>
      </ul>
      </>
    ),
  },
  // c8-station-types — tier 3
  {
    slug: "c8-station-types",
    title: "Staffed vs. self-service kiosks: a closer look",
    tier: 3,
    content: (
      <>
      <p className="mt-3"><strong>Audience:</strong> Admin deciding how to deploy stations.</p>
      <p className="mt-3"><strong>Outcome:</strong> You understand exactly what each station type can and can&apos;t do, and which to use where.</p>
      <p className="mt-3">This expands on the station-type choice in <strong>A1</strong>. The type is set at enrollment and can&apos;t be changed afterward, so it&apos;s worth understanding the difference.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What a staffed kiosk can do</h3>
      <p className="mt-3">A staffed kiosk has a volunteer present for every check-in. It can do everything:</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1">Regular check-in</li>
        <li className="mt-1">Checkout, including the blocked-pickup photo comparison</li>
        <li className="mt-1">Clearing a blocked-pickup gate when the operator confirms the person present isn&apos;t the blocked individual</li>
        <li className="mt-1">The &quot;I&apos;m here for pickup&quot; ping</li>
      </ul>
      <p className="mt-3">Because a trained person is making the call, a staffed kiosk is the only place where pickup and custody decisions happen.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">What a self-service kiosk can and can&apos;t do</h3>
      <p className="mt-3">A self-service kiosk sits at a turnstile-style entrance where families check themselves in without a volunteer hovering.</p>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Can:</strong> regular check-in</li>
        <li className="mt-1"><strong>Cannot:</strong> checkout &mdash; releasing a child always happens at a staffed kiosk, because the release gate is the parent&apos;s security code, not the device</li>
        <li className="mt-1"><strong>Cannot:</strong> clear a blocked-pickup entry &mdash; if a block applies, the family is routed to a staffed kiosk</li>
      </ul>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Why the limits exist</h3>
      <p className="mt-3">The restrictions aren&apos;t arbitrary. Releasing a child and clearing a custody restriction are judgment calls that a person has to make and stand behind. A self-service kiosk has no one to make that call, so it never does &mdash; which keeps those decisions defensible after the fact.</p>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Choosing per situation</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>Start staffed.</strong> For a first deployment, and for any entrance where pickups happen, use staffed kiosks</li>
        <li className="mt-1"><strong>Add self-service for volume.</strong> A high-traffic check-in-only entrance is a good fit for self-service, as long as pickups and any blocked-pickup households are handled at a staffed station</li>
      </ul>
      <figure className="my-4"><Image src="/help/checkin/c8-station-type-comparison.png" alt="C8 station type comparison" width={1280} height={720} className="rounded-lg border border-vc-border-light w-full h-auto" /></figure>
      <hr className="my-6 border-vc-border-light" />
      <h3 className="font-display text-lg font-semibold text-vc-indigo mt-6 mb-2">Related</h3>
      <ul className="list-disc pl-6 mt-3 space-y-1">
        <li className="mt-1"><strong>A1 &mdash; First-time kiosk setup</strong> (enrolling a station)</li>
        <li className="mt-1"><strong>B4 &mdash; Blocked-pickup entries</strong> (the gate self-service can&apos;t clear)</li>
      </ul>
      </>
    ),
  },
];
